[2025-05-08T00:01:03.066+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_and_selection.train_logistic_regression scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T00:01:03.087+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_and_selection.train_logistic_regression scheduled__2025-05-07T00:00:00+00:00 [queued]>
[2025-05-08T00:01:03.088+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-08T00:01:03.402+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_logistic_regression> on 2025-05-07 00:00:00+00:00
[2025-05-08T00:01:03.434+0000] {standard_task_runner.py:60} INFO - Started process 4800 to run task
[2025-05-08T00:01:03.451+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'training_and_selection', 'train_logistic_regression', 'scheduled__2025-05-07T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline_dag.py', '--cfg-path', '/tmp/tmpcwpegjhn']
[2025-05-08T00:01:03.453+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask train_logistic_regression
[2025-05-08T00:01:03.610+0000] {task_command.py:423} INFO - Running <TaskInstance: training_and_selection.train_logistic_regression scheduled__2025-05-07T00:00:00+00:00 [running]> on host 12febc400abb
[2025-05-08T00:01:03.823+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_and_selection' AIRFLOW_CTX_TASK_ID='train_logistic_regression' AIRFLOW_CTX_EXECUTION_DATE='2025-05-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-07T00:00:00+00:00'
[2025-05-08T00:01:03.835+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-08T00:01:03.835+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-08T00:01:14.954+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:01:14 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-08T00:01:19.274+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:01:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-05-08T00:01:19.473+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-05-08T00:01:19.812+0000] {logging_mixin.py:188} WARNING - Registered model 'diabetes_model' already exists. Creating a new version of this model...
[2025-05-08T00:01:19.863+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:01:19 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: diabetes_model, version 6
[2025-05-08T00:01:19.863+0000] {logging_mixin.py:188} WARNING - Created version '6' of model 'diabetes_model'.
[2025-05-08T00:01:19.885+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:01:19 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression at: http://10.43.101.187:30500/#/experiments/1/runs/8089ad07eb2c492888cde3a74fcc1260.
[2025-05-08T00:01:19.885+0000] {logging_mixin.py:188} WARNING - 2025/05/08 00:01:19 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://10.43.101.187:30500/#/experiments/1.
[2025-05-08T00:01:19.901+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-08T00:01:19.925+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=training_and_selection, task_id=train_logistic_regression, execution_date=20250507T000000, start_date=20250508T000103, end_date=20250508T000119
[2025-05-08T00:01:20.015+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-08T00:01:20.059+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
